### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by archercreat** [can1357/linux-pe#4]
Library says its linux-pe, yet there is no way to use it on linux.
What compiler should I use if not gcc-10 nor clang-11 can compile it?

**Comment by can1357** [comment]
I'm using clang-13 and it compiles just fine with -fms-extensions so I'd assume it also works fine with clang-11. Would be great if you could be more specific.

**Comment by can1357** [comment]
![image](https://user-images.githubusercontent.com/11807264/109418756-400ed280-79ca-11eb-83c8-824d75d61400.png)
Actually seems to work without -fms-extensions as well. I'm assuming you're missing the -std=c++20 switch, or it has to do with the STL you're using, eitherway you'll need to tell me the actual problem.

**Comment by can1357** [comment]
![image](https://user-images.githubusercontent.com/11807264/109419045-c546b700-79cb-11eb-9b16-d2feee0f2941.png)

I gave it a quick try and ran into some issues regarding headers but the latest push seems to have fixed it. Please re-open the issue and let me know the exact error if it persists.
