### ISSUE TITLE
compling errors

### ISSUE THREAD

**Issue by ghost** [can1357/linux-pe#9]
im getting these errors while compiling:
![image](https://github.com/can1357/linux-pe/assets/139636168/646f1bdf-3a1a-4b50-a46e-a8b5d9a85533)
![image](https://github.com/can1357/linux-pe/assets/139636168/67db29af-35ff-432a-af34-651f9a7224d9)
this is my CMake file:
![image](https://github.com/can1357/linux-pe/assets/139636168/db9cf450-bc06-40b3-bf79-03b6b952b607)
i already tried enabling fms extentions but it didnt do nothing

**Comment by CR3Swapper** [comment]
try using a newer version of clang instead of gcc. also @can1357 might be a good idea to list the minimum compiler requirements in the readme for this repo

**Comment by can1357** [comment]
It looks like the compiler you're using does not support C++20 requires statements. g++12 / clang++-14 should be supported, however I'm not entirely sure as to what the earliest version supported is.

**Comment by CR3Swapper** [comment]
> It looks like the compiler you're using does not support C++20 requires statements. g++12 / clang++-14 should be supported, however I'm not entirely sure as to what the earliest version supported is.

add that to the readme mr can 👁️
